<?php

/**
 * @file
 * Primary module hooks for Dog Utils
 */

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function dog_utils_plugin_filter_block__layout_builder_alter(array &$definitions) {
  // Se field name for available blocks in layout builder
  $allowed_blocks = [
    'inline_block:basic',
    'inline_block:carousel',
    'inline_block:carousel_item',
    'inline_block:drupal_gallery',
    'inline_block:galleria',
    'inline_block:hero',
    'inline_block:map',
    'inline_block:omeka_gallery',
    'inline_block:omeka_map',
    'inline_block:omeka_map_timeline',
    'field_block:node:page:body',
  ];

  foreach ($definitions as $definition => $def_value) {
    if (!in_array($definition, $allowed_blocks)) {
      unset ($definitions[$definition]);
    }
  }
}
