third_party_settings:
  field_group:
    group_container:
      label: Container
    group_content:
      label: Content
    group_settings:
      label: Settings
content:
  field_settings:
    settings:
      title: Paragraph
      title_plural: Paragraphs
