third_party_settings:
  field_group:
    group_container:
      label: Container
    group_slides:
      label: Slides
    group_settings:
      label: Settings
    group_carousel_behaviours:
      label: 'Carousel behaviours'
content:
  field_settings:
    settings:
      title: Paragraph
      title_plural: Paragraphs
  field_slides:
    settings:
      title: Paragraph
      title_plural: Paragraphs
