third_party_settings:
  field_group:
    group_container:
      label: Container
    group_place:
      label: Place
    group_settings:
      label: Settings
content:
  field_location:
    settings:
      path: '{"color":"#3388ff","opacity":"1.0","stroke":true,"weight":3,"fill":"depends","fillColor":"*","fillOpacity":"0.2","radius":"6"}'
  field_settings:
    settings:
      title: Paragraph
      title_plural: Paragraphs
