third_party_settings:
  field_group:
    group_container:
      label: Container
    group_content:
      label: Content
    group_settings:
      label: Settings
      format_settings:
        description: 'Docs for <em>Container classes</em> field: <a href="https://italia.github.io/bootstrap-italia/docs/componenti/sections/#colori-di-sfondo" title="Read the Docs" target="_blank">https://italia.github.io/bootstrap-italia/docs/componenti/sections/#colori-di-sfondo</a>'
content:
  field_settings:
    settings:
      title: Paragraph
      title_plural: Paragraphs
