label: 'Image filter'
description: 'If checked, a filter is added as described in the <a href="https://italia.github.io/bootstrap-italia/docs/componenti/hero/#con-overlay-e-filtro-di-colore-primario" title="Read the Docs" target="_blank">Docs</a>.'
settings:
  on_label: 'On'
  off_label: 'Off'
