label: 'Call to action type'
description: 'Choose button type. Default: <em>Outline primary</em>. <a href="https://italia.github.io/bootstrap-italia/docs/utilities/colori/" title="Read the docs" target="_blank">Docs</a>'
