label: Node
description: 'To manage types go to <a href="/admin/structure/paragraphs_type/node_reference/fields/paragraph.node_reference.field_node" title="Click to choose types">Structure -> Paragraphs types -> Node Reference -> Manage fields -> Edit Node Field</a>'
