label: 'Callout display'
description: 'Docs: <a href="https://italia.github.io/bootstrap-italia/docs/componenti/callout/" target="_blank" title="Read the Docs">https://italia.github.io/bootstrap-italia/docs/componenti/callout/</a>'
