label: 'File legacy'
description: 'Upload one or more files from your device. If you want to attach a file that has already been uploaded, use the <em>File Browser</em> by positioning yourself in the <strong>public://attachments</strong> folder.'
