label: 'Callout variant'
description: 'Docs: <a href="https://italia.github.io/bootstrap-italia/docs/componenti/callout/" title="Docs" target="_blank">https://italia.github.io/bootstrap-italia/docs/componenti/callout/</a>'
