label: 'Accordion flush'
description: 'Enable to remove the default background color, some borders, and some rounded corners to render accordions edge-to-edge with their parent container.'
settings:
  on_label: 'On'
  off_label: 'Off'
