label: 'Overlay color'
description: 'Choose the color of the overlay. In this version only <em>Primary</em> work. <a href="https://italia.github.io/bootstrap-italia/docs/componenti/hero/#con-overlay-di-colore-primario" title="Read the Docs" target="_blank">Docs</a>'
