label: 'Gallery grid type'
description: '<a href="https://italia.github.io/bootstrap-italia/docs/organizzare-i-contenuti/liste-di-immagini/#tipi-di-griglia" title="Read the docs" target="_blank">Docs</a>'
